apiVersion: v1
kind: Service
metadata:
  name: {{ include "myservice.fullname" . }}
  #namespace: {{ .Values.global.namespace.nchdDMZNamespace }}
  labels:
    {{- include "myservice.labels" . | nindent 4 }}
  #annotations:
  # Note that the backend talks over HTTP.
  # service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
  # TODO: Fill in with the ARN of your certificate.
  #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:317167322404:certificate/2546620e-6d80-4e07-919b-d2367ac5bfde
  # Only run SSL on the port named "https" below.
  #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  selector:
    {{- include "myservice.selectorLabels" . | nindent 4 }}
    #app: grid
  ports:
    - name: http
      port: 80
      targetPort: 4080
    - name: https
      port: 443
      targetPort: 4080
  type: ClusterIP